allowerCommerceUrl= https://allovercommerce.com/
username1as = woody1
signInEmail1 = woody.ansley@feerock.com
signInPassword1 = Sifre123456?
signInEmail2 = raydin.nathanael@feerock.com
signInEmail3 = aris.saw@feerock.com
yeniEmail = raymere.germaine@feerock.com
yeniUsername = Black15
yeniUsername2 = Pink10
hataliEmail1 = black05.pink.com
hataliemail2= blackpink@feerock
password8 = Sifre12?
password9 = Sifre123?
password7= Sifre1?
passwordRakam = 123456789
yeniUsername3= Username1*
signInEmail4 = jossiel.lavante@feerock.com
signInEmail5 = karnell.jordyan@feerock.com

alloverCommerceUrlME = https://allovercommerce.com/
browser = chrome
emailSignInME=brennon.jeziel@feerock.com
emailKutusuSifreME = 1234##
postcodeME=35100
phoneNumberME=5554750251
provinceNameME=Adana
productTitle=title
shortDescription=beyaz gomlek
descriptionGomlek=uzun kollu

tooshort=ENSAR
tooshort2=/////
weak=Ensare
weak2=aabc�de
good=ensar.27
good2=123456ab
strong=Ensar**
strong2=Ensar/**
vendorSayfasi=Vendor Registration
short=Too short
alloverUrl=https://allovercommerce.com/
UserNameE=marquese.levell@feerock.com
PasswordE=eNSAR.123

browserHK = chrome
allovercommerceURLHK = https://allovercommerce.com/
usernameHK = frances.bryken@feerock.com
passwordHK = Deneme123Deneme
usernameHK2 = kamdyn.zeyden@free2ducks.com
passwordHK2 = Deneme123Deneme

allovercommerceUrl=https://allovercommerce.com
email1=qusay.enrique@feerock.com
usernamemeMo=Meryoz
passwordMo=ozgn123456.
degistirilecekFirstName=mery
degistirilecekLastName=mery
degistirilecekCompanyName=mery
degistirilecekCountry=Turkey
degistirilecekAdressIlkBox=mery
degistirilecekAdresIkinciBox=mery
degistirilecekPostcode=71000
degistirilecekTown=Ankara
degistirilecekProvince=Ankara
degistirilecekDisplayName=mery
biography=Celladina asik olmssa bir millet Ister ezan, ister �an dinlet Itiraz etmiyorsa s�r� gibi illet Mustehaktir ona her t�rl� zillet.
degistirilecekPassword=ozgn123456.

alloverCommerceUrls� = https://allovercommerce.com/
email =  = misnoku1@gmail.com
password = Misnokistan
browser = chrome

allowerCommerceUrlMe = https://allovercommerce.com/
FakerUrl = https://www.fakemail.net/
userhb= long
passwordhb=12345hilalb
urun = Kitap
urun2 = kalem
lastnamehb = kase
streethb = 8149 Stark Springs, South Xuan, CT 46780-5263
zipcodecodehb = 66010
cityhb = Ankara
phoneHb = 0555 555 55 55
mailHb = long.kase@free2ducks.com











































